---
title: "Weather Exploration"
output: pdf_document
---

```{r}
library(tidyverse)

library(plotly)
```

```{r}
ufo_weather <- read_csv("UFO_and_Weather.csv")
```

```{r}
ufo_weather
```

# kill non-us states 

```{r}
ufo_weather <- subset(ufo_weather, !(state %in% c("BC", "QC", "ON", "NS", "AB", "MB", "SK", "YT", "NL")))
  
ufo_weather
```



```{r}
head(ufo_weather)
```

```{r}
ufo_count_nas_weather <- ufo_weather %>%  
  mutate(weather_na_count = rowSums(is.na(select(., c(temperature, relative_humidity, precipitation, snow, wind_direction, wind_speed)))))

ufo_count_nas_weather
```
Take out observations that could not retrieve weather data for 

```{r}
ufo_weather <- ufo_count_nas_weather %>% 
  filter(weather_na_count < 6)

ufo_weather
```
snow is always NA 
```{r}
summary(ufo_weather) 
```
```{r}
ufo_weather %>% 
  drop_na(precipitation) %>% 
  filter(precipitation > 0) %>% 
  group_by(shape) %>% 
  summarise(shape_count = n()) %>% 
  arrange(desc(shape_count))
```

```{r}
ufo_weather %>% 
  group_by(shape) %>% 
  summarise(shape_count = n()) %>% 
  arrange(desc(shape_count))
```

Rain does not seem to be related to the shape of the UFO that people saw 

```{r}
ufo_weather_dropnatmp <- ufo_weather %>% 
  drop_na(temperature)

ggplot(ufo_weather_dropnatmp , aes(x = temperature)) +
      geom_histogram(aes(y = ..density..), colour = "black", fill = "white") +
      geom_density(alpha = .2, fill="#FF6655") 
```
```{r}
library(lubridate)
library(scales) 
```

```{r}
ggplot(data = ufo_weather_dropnatmp, aes(x=date_time, y=temperature)) +
  geom_point(na.rm=TRUE, color="darkolivegreen4", size=1, pch=20) +
  scale_y_continuous(breaks = seq(-50, 60, 10), limits=c(-30, 50)) +
  scale_x_datetime(breaks=date_breaks("1 year"), labels = date_format("%b %Y")) + 
  ggtitle("Air Temperature at Reported UFO Sighting Sites 2015-2019") +
  xlab("Date") + 
  ylab("Temperature (Celsius)") +
  theme_minimal()
```

```{r}
ufo_weather_dropnatmp_madar <- ufo_weather_dropnatmp
contains_madar <- grepl('MADAR', ufo_weather_dropnatmp_madar$text)

ufo_weather_dropnatmp_madar <- cbind(ufo_weather_dropnatmp_madar, contains_madar)
ufo_weather_dropnatmp_madar
```

```{r}
unique(ufo_weather_dropnatmp_only_madar$text)
```
```{r}
ufo_weather_dropnatmp_madar <- ufo_weather_dropnatmp_madar %>% 
  filter(text != "Four pairs of orbs went W-E in 6 mins then turned SE.  Cell phone images or video.  Story appeared in local paper and on TV.  Jet described as military was taking same path but local radar showed only a commercial jet at 37,000'.  These objects traveled 15 mi in 6 mins in 4 prs, so this would be very fast, too fast for jackolanterns which would take 15-20 for each pair.  Was investigated by colleague for the MADAR Center at Newburgh." & text != "Three witnesses observed an object that maneuvered in different directions Orb of white light flashing intermittently and changing direction over livestock farmland. Seven hours after alert and 92 miles from MADAR site.  Primary witness, his brother, and girlfriend were outside when they noticed a white, intermittently flashing orb hovering behind trees in his backyard.  It resembled car’s headlight but there was no road there.  It disappeared and then reappeared seconds later above the treetops, flashing for a few seconds then disappeared again.  It reappeared behind the trees, downward and to the right of where it was just seconds prior.  Witnesses were freaked out and went inside the witness home and watched from the window to see if it reappeared, but it didn’t.  It made no noise.  Witness suspected it was possibly a drone but nobody lives anywhere even close to where the light appeared to be." & text != "Witness encountered bright white light that approached her car  from the left and then  zipped to the right Witness was on her way home from work and when approaching the first marker (on the map), got a clear view of a bright, white light over to her left. (See the Black Star on Annotated Map.) Object was previously obscured by trees, but as her vehicle made the turn around the bend in the road, it came into view.  She had not seen or known about it before getting to that spot.  It was moving slowly in an angle to the right but coming towards her.  It appeared to be moving slow and in her general direction.  The flight path seemed to be more or less level in flight, neither ascending or decending.  When she drove further down the road to where the second marker is on the map, that's when it immediately zipped off to the right and disappeared. (See the Black Star on the Annotated Map.)  It was a very quick maneuver that didn't go up or down from there..just off to the right in her field of view.  The other strange part about this was that when it shot off to the right, i! t seemed to disappear while in full view, just kind of winked out.  There were no trees in the way or anything obscuring the view when that happened.  She slowed down and began trying to see if she could find it again but to no avail.  When she continued down the road to the third marker on the map, she saw a helicopter (marked as a blue star) which she thought might be lifeflight as they fly up from Nashville and often take people to the hospital down there.  It had more than just the white lights so she knew it was something normal. At this point, she was about to tum off of 101st when she called her husband to tell him to check his MADAR unit. The phone call was made at 9:33 pm.  She was only a minute or two away from the house when she made that call. (Residence is indicated using a Red Star on the Annotated Map.)")
```

```{r}
ufo_weather_dropnatmp_madar %>% 
  group_by(contains_madar) %>% 
  summarise(count=n())
```

```{r}
ufo_weather_dropnatmp_madar %>% 
  group_by(contains_madar) %>% 
  summarise(avg_tmp = mean(temperature))
```

```{r}
ufo_weather_madar_nodes_by_state <- ufo_weather_dropnatmp_madar %>% 
  filter(contains_madar == TRUE) %>% 
  group_by(state) %>%
  summarise(count_nodes = n()) %>% 
  arrange(desc(count_nodes))

ufo_weather_madar_nodes_by_state 
```

```{r}
ufo_weather_dropnatmp2 <- ufo_weather_dropnatmp %>% 
  group_by(state) %>% 
  summarise(avg_tmp = mean(temperature))

ufo_weather_dropnatmp2
```


```{r}
l <- list(color = toRGB("white"), width = 2)
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
fig <- plot_geo(ufo_weather_madar_nodes_by_state, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    z = ~count_nodes, text = ~count_nodes, locations = ~state,
    color = ~count_nodes, colors = 'Purples'
  )
fig <- fig %>% colorbar(title = "# of Madar Nodes")
fig <- fig %>% layout(
    title = 'UFO recordings by MADAR Nodes in the US from 2015-2019',
    geo = g
  )
fig
```


```{r}
l <- list(color = toRGB("white"), width = 2)
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
fig <- plot_geo(ufo_weather_dropnatmp2, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    z = ~avg_tmp, text = ~avg_tmp, locations = ~state,
    color = ~avg_tmp, colors = 'Purples'
  )
fig <- fig %>% colorbar(title = "Temperature")
fig <- fig %>% layout(
    title = 'Average Temperature of UFO Sightings in the US from 2015-2019',
    geo = g
  )
fig
```


```{r}
ufo_weather_sightings_by_state <- ufo_weather_dropnatmp_madar %>% 
  group_by(state) %>% 
  summarise(sightings = n()) %>% 
  arrange(desc(sightings))

ufo_weather_sightings_by_state 
```


```{r}
ufo_nodes_and_sightings <- merge(x=ufo_weather_madar_nodes_by_state, y=ufo_weather_sightings_by_state , by="state")
ufo_nodes_and_sightings <- ufo_nodes_and_sightings%>% 
  mutate(percent_node = count_nodes / sightings * 100) %>% 
  arrange(desc(percent_node))

ufo_nodes_and_sightings
```


```{r}
ggplot(data = ufo_nodes_and_sightings) +
  geom_bar(mapping = aes(x = reorder(state, -percent_node), y = percent_node), stat = "identity", fill = "#76A422") +
  labs(title="% of Sightings Reported by MARDAR Nodes by State", 
            y="Percent of Sightings Reported by MARDAR Nodes", 
            x="State") +
  theme_minimal()

```
```{r}
ufo_weather
```

```{r}
ufo_weather %>% 
  filter(month == 8) %>% 
  group_by(day) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```


```{r}
ggplot(data = ufo_weather_dropnatmp, aes(x=date_time, y=temperature)) +
  geom_point() +
  scale_y_continuous(breaks = seq(-50, 60, 10), limits=c(-50, 60)) +
  facet_wrap(~ shape)
```

```{r}
ggplot(ufo_weather_dropnatmp, aes(x = temperature)) +
  geom_histogram(aes(y = ..density..), colour = "black", fill = "white") +
  geom_density(alpha = .2, fill="#FF6655") +
  facet_wrap(~ shape)
```

```{r}
ufo_weather_dropnawd <- ufo_weather %>% 
  drop_na(wind_direction)

ggplot(ufo_weather_dropnawd , aes(x = wind_direction)) +
      geom_histogram(aes(y = ..density..), colour = "black", fill = "white") +
      geom_density(alpha = .2, fill="#FF6655") 
```

```{r}
ggplot(ufo_weather_dropnawd, aes(x = wind_direction)) +
  geom_histogram(aes(y = ..density..), colour = "black", fill = "white") +
  geom_density(alpha = .2, fill="#FF6655") +
  facet_wrap(~ shape)
```

```{r}
ufo_weather_dropnaws <- ufo_weather %>% 
  drop_na(wind_speed)

ggplot(ufo_weather_dropnaws , aes(x = wind_speed)) +
      geom_histogram(bins = 30, aes(y = ..density..), colour = "black", fill = "white") 
```
```{r}
ggplot(ufo_weather_dropnaws, aes(x = wind_speed)) +
  geom_histogram(aes(y = ..density..), colour = "black", fill = "white") +
  geom_density(alpha = .2, fill="#FF6655") +
  facet_wrap(~ shape)
```
```{r}
ufo_weather_md <- ufo_weather %>% 
  group_by(month, day) %>% 
  summarise(count= n()) %>% 
  mutate(monthday = paste(month, day))


ufo_weather_md
```
```{r}
ufo_weather %>% 
  group_by(year) %>% 
  summarise(count = n())
```

